### ISSUE TITLE
cudnn version

### ISSUE THREAD

**Issue by EliotChenKJ** [ningyu1991/TextureMixer#3]
Hi, 
ur works are truly impressive. but  i've tried to use ur code for training customed images. i found out that:
 - almost all 7.1.x versions of cuDNN can't work well in ur code;
 - it finnally worked when i also tested cuDNN with version 7.0.5;
i was wondering that maybe you've recorded the wrong cuDNN version?

Error warning:
![image](https://user-images.githubusercontent.com/48468233/83243966-466ce580-a1d1-11ea-9898-92657324226a.png)

Also, will the "--export_labels" argument in dataset_tool.py be needed when training ur network in big datasets?

Hope that u can help me deal with these problems :) .
best wishes.

**Comment by ningyu1991** [comment]
We built our code from the [progressive growing GAN repo](https://github.com/tkarras/progressive_growing_of_gans). They state "NVIDIA driver 391.25 or newer, CUDA toolkit 9.0 or newer, cuDNN 7.1.2 or newer", which works on our end. Is that because your cuDNN and CUDA version did not match? But anyway, glad you've worked it out!

"--export_labels" is an argument inherited from the progressive growing GAN repo, which is not used in our paper, because our paper focuses on mixing texture images from the same label (Earth, Animal Fur, Plants, etc), regardless of the dataset size.

Hope these help!

**Comment by EliotChenKJ** [comment]
Hi, when it comes to environment building, all kinds of variants are indeed hard to trace. Also, i know the "--EXPORT_LABELs" option now. Thank for ur answer :).

Best wishes.
